<?php
/** @var \Justuno\M2\ViewModel\ScriptViewModel $viewModel */
/** @var \Justuno\M2\Block\Script $block */
$viewModel = $block->getViewModel();
$viewModel = $block->getViewModel();
$apiKey = $block->getApiKey();
$subDomain = $block->getSubDomain();
$baseURL = "https://" . $block->escapeJs($subDomain);
$url = "https://justone.ai/embed/ju_magento_init.js?v=2";
$isProductPage = $viewModel->isProductPage();
$productId = $viewModel->getProductId();
$orderData = $viewModel->getOrderData();
$currencyCode = $block->getCurrentCurrencyCode();
?>

<script>
    window.ju4Config = <?= /* @noEscape */ json_encode([
        'auth' => $apiKey,
        'num' => $apiKey,
        'assetHost' => "https://justone.ai/embed",
        'pApi' => $baseURL
    ]) ?>;
    window._juplatformtype = "magento";
    window.ju4_auth = window.ju4Config.auth;
    window.ju4_num = window.ju4Config.num;
    window.ju4_asset_host = window.ju4Config.assetHost;
    window.ju4_pApi = window.ju4Config.pApi;
    window.ju4_api = "https://api.justuno.com";
    
    <?php if ($viewModel->isCustomerLoggedIn()): ?>
    window._jucustId = "<?= $block->escapeJs($viewModel->getCustomerId()) ?>";
    window._jucustomId = "<?= $block->escapeJs($viewModel->getCustomerId()) ?>";
    <?php endif; ?>
    <?php if ($isProductPage && $productId): ?>
    window._jupagetype = "product";
    window._juprodId = "<?= $block->escapeJs($productId) ?>";
    <?php endif; ?>
</script>

<script data-cfasync="false">
    (function(i,s,o,g,r,a,m){i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)};a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script',ju4_asset_host+'/ju_magento_init.js?v=2','ju4app');
</script>

<script type="text/x-magento-init">
{
    "*": {
        "Justuno_M2/js/justuno": {
            "orderData": <?= /* @noEscape */ $orderData != null ? json_encode($orderData) : 'null' ?>,
            "customJs": "<?= $block->escapeJs($block->getCustomJsContent()) ?>",
            "version": "<?= time() ?>",
            "currencyCode": "<?= $block->escapeJs($currencyCode) ?>"
        }
    }
}
</script>
